[package]
name = "walle_poc"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = "1"
log = "0.4"
lambda_http = "0.7.1"
ed25519-dalek = "1.0.1"
http = "0.2.8"
hex = "0.4.3"
anyhow = "1.0.66"
serde_json = "1.0.87"
